# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('condition', models.CharField(choices=[('sunny', 'Sunny'), ('overcast', 'Overcast'), ('rainy', 'Rainy')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.IntegerField()),
                ('two', models.IntegerField()),
                ('three', models.IntegerField()),
                ('four', models.IntegerField()),
                ('five', models.IntegerField()),
                ('six', models.IntegerField()),
                ('seven', models.IntegerField()),
                ('eight', models.IntegerField()),
                ('nine', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IT_short_course.Match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IT_short_course.Player')),
            ],
        ),
    ]
